# Generated by Django 3.2.5 on 2022-05-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travellozone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_Up_Users',
            new_name='User',
        ),
    ]
