# Generated by Django 3.2.5 on 2022-05-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travellozone', '0003_auto_20220516_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
