# Generated by Django 3.2.5 on 2022-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travellozone', '0004_auto_20220516_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Sign_Up_User',
        ),
    ]
